services:
  qemu:
    image: BangFy/qemu
    container_name: qemu
    environment:
      BOOT: "arch"
      BOOT_MODE: "lagacy"
      RAM_SIZE: "16G"
      CPU_CORES: "4"
      DISK_SIZE: "200G"
      DISK_TYPE: "blk"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
    volumes:
      - ./qemu:/storage
    restart: always
    stop_grace_period: 2m
